apiVersion: apps/v1
kind: Deployment
metadata:
  name: annontator-1
  labels:
    app: annontator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: annontator
  template:
    metadata:
      labels:
        app: annontator
    spec:
      serviceAccount: annontator-sa
      containers:
        - name: annontator
          image: nightowl98/annontator:v2.8
          imagePullPolicy: Always

          
